version: '3'
services:
  api:
    build: .
    depends_on:
     - redis
    command: python3 -m flask run --host 0.0.0.0 --port 3445
    ports:
     - "3445:3445"
    env_file:
     - .env
  redis:
    image: "redis:alpine"
